name: Continuous Integration

on: [push, pull_request]

jobs:
  client-build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "21.2"

      - name: Install Client Dependencies
        run: cd client && npm install

      - name: Run lint
        run: cd client && npm run lint

      - name: Build Client
        run: cd client && npm run build

  server-setup:
    needs: client-build-and-lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "21.2"

      - name: Install Server Dependencies
        run: cd server && npm install

      - name: Run lint
        run: cd server && npm run lint

    # Placeholder for future server-side testing
    # - name: Run Server Tests
    #   run: cd server && npm test
